name: react-deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18.17.0'

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: Deploy to GitHub Pages
        run: |
          git config --global user.email "cofcsave@gmail.com"
          git config --global user.name "cofcsave"
          cd dist
          echo 'rkaero.com' > CNAME
          git init
          git add -A
          git commit -m 'Deploy to GitHub Pages'
          git push --force "https://${{ secrets.ACCESS_TOKEN }}@github.com/${{ github.repository }}.git" master:gh-pages
